CREATE TABLE ufs
(
	id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	sigla VARCHAR(2) NOT NULL,
	nome VARCHAR(19) NOT NULL,
	CONSTRAINT pkufs PRIMARY KEY(id)
);

CREATE TABLE cidades
(
	id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	iduf BIGINT NOT NULL,
	nome VARCHAR(60) NOT NULL,
	CONSTRAINT pkcidades PRIMARY KEY(id),
	CONSTRAINT fkcidades1 FOREIGN KEY(iduf) REFERENCES ufs(id)
);

CREATE TABLE bairros
(
	id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	idcidade BIGINT NOT NULL,
	nome VARCHAR(72) NOT NULL,
	CONSTRAINT pkbairros PRIMARY KEY(id),
	CONSTRAINT fkbairros1 FOREIGN KEY(idCidade) REFERENCES cidades(id)
);

CREATE TABLE enderecos
(
	id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	idbairro BIGINT NOT NULL,
	logradouro VARCHAR(100) NOT NULL,
	complemento VARCHAR(100),
	cep VARCHAR(8) NOT NULL,
	CONSTRAINT pkenderecos PRIMARY KEY(id),
	CONSTRAINT fkenderecos1 FOREIGN KEY(idbairro) REFERENCES bairros(id)
);